services:
  - type: web
    name: futureal
    env: static
    buildCommand: cd AdminPannel && npm install && npm run build
    staticPublishPath: ./AdminPannel/dist
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
